### ISSUE TITLE
Замечание экзамен js

### ISSUE THREAD

**Issue by AndriiLitvin** [luckyNata/luckyNata.github.io#21]
1. Все внешние скрипты должны быть скачаны и конкатенироваться, минифицироваться в vendor.min.js и подключаться
2. В dest/css/ нет ie8.css
3. Зачем эта вложенность `<div><a href="#" class="register_style register_style--sign">Sign up</a></div><div><a href="#" class="register_style">Log in</a></div>` 
можно свободно обойтись без нее. или просто создать один блок и там две ссылки

4. 
```
<div>
  <div class="item-photo">
    <img src="img/partner1.png">
    <img src="img/circle1.png" class="item-icon">
  </div>
  <p class="item-name">Bradley Hunter</p>
  <p class="item-hobby">Based in Chicago. I love playing tennis and loud music.</p>
</div>
```
 опять за лишьний div,  вот так 
```
  <div class="item-photo icon-circle1">
    <img src="img/partner1.png">
    <p class="item-name">Bradley Hunter</p>
    <p class="item-hobby">Based in Chicago. I love playing tennis and loud music.</p>
  </div>
```
где
 ```
icon-circle1:before {
    content: "";
    background: url('img/circle1.png');
    width: 41px;
    position: absolute;
    top: 87px;
    left: 85px;
}
```

**Comment by AndriiLitvin** [comment]
хотя я подумал блок тот нужен)) только назвать его как то нужно. будет так 
```
<div>
  <div class="item-photo icon-circle1">
    <img src="img/partner1.png">
  </div>
  <p class="item-name">Bradley Hunter</p>
  <p class="item-hobby">Based in Chicago. I love playing tennis and loud music.</p>
</div>
```

**Comment by luckyNata** [comment]
Изменила, работает в IE

**Comment by AndriiLitvin** [comment]
1, добавь ховер кнопкам
2,сделай чтоб при клике на плитке на картинку она открывалась в попапе
3 ,поправь в ие шрифты и вот это
![image](https://cloud.githubusercontent.com/assets/13675947/14065002/9a63ab96-f420-11e5-860d-87d89edbd897.png)
![image](https://cloud.githubusercontent.com/assets/13675947/14065003/a29ce44e-f420-11e5-9f89-66bd4d79b5da.png)
![image](https://cloud.githubusercontent.com/assets/13675947/14065004/ae871234-f420-11e5-9fda-0e4229484381.png)

**Comment by luckyNata** [comment]
Исправила, посмотри, пожалуйста

**Comment by AndriiLitvin** [comment]
с ИЕ никаких улучшений. у тебя в тестере все норм? текст накрайняк добавь везде sans-serif
у тебя не работают условия.. посмотри вот эту статью может поймешь в чем дело https://habrahabr.ru/post/198488/

тут я посмотрел 15 пункт в ТЗ и там тож нужно сделать кое что там "При первой загрузке страницы в плитке должны выводиться случайные картинки"  тоесть все с разною тематикою. ну глянь макет.

**Comment by AndriiLitvin** [comment]
Зачет
