### ISSUE TITLE
Замечания по работе 5.1 cadastre

### ISSUE THREAD

**Issue by AndriiLitvin** [luckyNata/luckyNata.github.io#4]
http://joxi.ru/VrwlE7qFZneVmX
1)тут не ховер а при фокусе
2)Сайт на всю страницу
3) бекграунд не должен повторятся, добавь размер бекграунда

**Comment by AndriiLitvin** [comment]
http://joxi.ru/Y2L0zPXs3GWg26
1),3) отцентрируй
2)Кнопку сверстать а не картинкой

**Comment by luckyNata** [comment]
сделала

**Comment by AndriiLitvin** [comment]
а это http://joxi.ru/DmBD8bNuXlGxAP

**Comment by luckyNata** [comment]
Сделала :)

**Comment by AndriiLitvin** [comment]
http://joxi.ru/EA4vLykFdEgjmb
1)Присмотрись в макете на меню в хедере , там структура не такая(фон) + при ресайзе окна менюшка улетает вправо. там нужно добавить контейнер на хедер ему сделать фиксированую ширину 1215рх и выровнять по центру маргинами и туда пихнуть контент хедера.
2)цвет на кнопке белый и по моему жирный.

**Comment by luckyNata** [comment]
сделала вроде бы...

**Comment by AndriiLitvin** [comment]
с .wrapper  position: fixed убери а то скрол не работает. перемести бекграунд с велосипедистами в боди.

**Comment by luckyNata** [comment]
переместила

**Comment by AndriiLitvin** [comment]
ЗАЧЕТ
