### ISSUE TITLE
Замечания по экзамену 7-9

### ISSUE THREAD

**Issue by AndriiLitvin** [luckyNata/luckyNata.github.io#7]
+ убрать горизонтальный скролл.
+ по всем макету должен быть text-shadow
смотрел на МОзиле

Экран 960 http://joxi.ru/v29l3qWFGGNqKm
-
как то странно себя ведет. ка видишь большие отступы
1) стрелочки должны быть на одинаковом расстоянии 
2)нет триугольничка
3)6) тут отступов не должно быть
4) все должно быть выровняно
5)видно эту область, убрать

Экран 768 http://joxi.ru/Vm67Z8Qsxxb5k2
-
тоже самое что и макета 960

Экран 480 http://joxi.ru/KAgGg68tgg70OA
-
+ вообще не соответствует макету

1)Меню не то
2)стрелочки должны бить в контейнере с контентом
3)этого блока нет
4)тень
5)все остальние блоки не соответствуют макету

Экран 320 http://joxi.ru/nAy8vNqFXXbLL2
-
1)отцентрировать
2) тут нет айфона
3)Должно быть в одну строчку
4)Отцентрировать
5)нет менюшки

у тебя по идеи макеты попутаны

там такие ширины экранов: 320-479(макет 320), 480-767( макет 480), 768-959(макет 768), 960- ++(макет 960 только тут фиксированая максимальная ширина, чтоб не улетало все)

**Comment by luckyNata** [comment]
Поправила

**Comment by AndriiLitvin** [comment]
Экран 960 http://joxi.ru/1A5pK7zFKnvQW2 
-
1) отцентрируй
2) подправь футер.он шире и надпись "Designed by Pingbull AS" чутка ниже менюшки

Экран 768 http://joxi.ru/Vm67Z8QsxD11a2 
-
1)нужен отступ.

Экран 480
-
1) http://joxi.ru/8AnVER6uqjXwbA  - залазит под айфоны
2) http://joxi.ru/l2Z64PNu8wOMR2 - должно быть вровень с контентом
3)http://joxi.ru/eAO1zP7i4xQbam - отцентрируй

**Comment by luckyNata** [comment]
исправила замечания

**Comment by AndriiLitvin** [comment]
Экран 960 http://joxi.ru/brR6zPluQJRD4r
-
1) переместить право

Экран 768 http://joxi.ru/BA0v5XpFBJ8Ygm 
-
1)Выровнять
2)тут не надо менять иконки они такие же как и и на макете 960

Экран 480 http://joxi.ru/p277aN5s0odPO2 
-
1)2)3) выровнять
4) в одну строку

Экран 320 http://joxi.ru/8AnVER6uqj9OlA
-
1)не работает
2)этот блок шире + навигация внизу по центру
3) вировняй вертикально как то смотриться стремно

**Comment by luckyNata** [comment]
исправила замечания

**Comment by AndriiLitvin** [comment]
Экран 320
http://joxi.ru/brR6zPluQJeger 
http://joxi.ru/krDDzYOu0EvPyr 
http://joxi.ru/V2VKbPBC0x3peA
 -  убери отступ в %

**Comment by luckyNata** [comment]
Проверь, пожалуйста

**Comment by AndriiLitvin** [comment]
Экран 960 
-
http://joxi.ru/Dr8ERJ6Fkola7m - сдвинь вправо

Экран 480 
-
http://joxi.ru/Y2L0zPXsn7GjD2 - отцентрируй

Экран 320 
-
http://joxi.ru/MAjlEL1Fvj7p8m - отцентрируй
http://joxi.ru/gmvgpyqtxqN4z2 - логотипы в два ряды

**Comment by luckyNata** [comment]
Привет. Я исправила

**Comment by AndriiLitvin** [comment]
Экран 960 
-
1) http://joxi.ru/p277aN5s0KP0x2- подыми выше
2) http://joxi.ru/5mdMgP7iv39vR2-эти блоки по высоте одинаковые

**Comment by luckyNata** [comment]
исправила

**Comment by AndriiLitvin** [comment]
ЗАЧЕТ
